# Generated by Django 6.0.6 on 2026-07-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("singer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="singer",
            name="name",
            field=models.CharField(default="unknown", max_length=50),
            preserve_default=False,
        ),
    ]
