# Generated by Django 6.0.6 on 2026-07-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("singer", "0002_singer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="title",
            field=models.CharField(default="unkwon", max_length=100),
            preserve_default=False,
        ),
    ]
