# Generated by Django 6.0.6 on 2026-07-14 10:56

import singer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("singer", "0003_song_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="singer",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=singer.models.image_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="singer",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="singer",
            name="tags",
            field=models.ManyToManyField(blank=True, to="singer.tag"),
        ),
    ]
